# Generated by Django 3.2.23 on 2023-11-24 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderListItem',
            new_name='OrderLineItem',
        ),
    ]
