# Generated by Django 3.2.23 on 2024-01-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobapplication_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.CharField(choices=[('Store Manager', 'Store Manager'), ('Sales Manager', 'Sales Manager'), ('Delivery Driver', 'Delivery Driver'), ('Delivery Driver (International)', 'Delivery Driver (International)')], max_length=50, null=True),
        ),
    ]
