# Generated by Django 3.2.23 on 2024-02-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_jobapplication_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='phone_number',
        ),
    ]
