# Generated by Django 3.2.23 on 2023-11-26 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcomments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductComments',
        ),
    ]
